spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/elkhayer
        username: abderrahman
        password: haouate20010811
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: Abderrahmanehaouate@gmail.com
        password: ipsi hekl ecwr lqdv
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true